### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by broadsw0rd** [librpc/web#6]
```yaml
deploy:
  provider: npm
  email: broadsw.rd@yandex.ru
  api_key: $AUTH_TOKEN
  on:
    tags: true
```
